# application.yml  (공통 환경 설정)

spring:
  profiles:
    active: dev # 기본 프로파일을 dev로 설정

  web:
    resources:
      add-mappings: false # Spring Boot의 기본 리소스 매핑(예: /webjars) 비활성화

  jpa:
    open-in-view: false  # [실무 권장] OSIV 종료 (기본값은 true)
    properties:
      hibernate:
        # 1:N 관계를 IN 절로 묶어서 조회하는 설정
        # 100~500 사이가 성능과 메모리 효율 면에서 가장 적절합니다.
        default_batch_fetch_size: 100

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100 #페이징 아무리 크게 보내도 100개로 제한


